language: node_js
node_js:
   - "0.10"
   - "0.12"
   - "4"
script:
   npm test
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database pg_promise_test;' -U postgres
  - node test/db/init.js
branches:
  only:
    - master
env:
  - BLUEBIRD_DEBUG=0
