language: node_js
sudo: required
matrix:
  include:
  - node_js: "7"
    script: "npm test"
  - node_js: "8"
    script: "npm run travis"
  - node_js: "12"
    script: "npm run travis"
addons:
  postgresql: "9.6"
before_script:
- psql -c 'create database pg_promise_test;' -U postgres
- node test/db/init.js
env:
- BLUEBIRD_DEBUG=0
