language: node_js
node_js:
   - "0.12"
   - "0.10"
   - "iojs"
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database pg_promise_test;' -U postgres
  - node test/db/init.js
branches:
  only:
    - 2.0
env:
  - BLUEBIRD_DEBUG=0
